variable "varenvrg" {}
variable "varenvvn" {}
variable "varenvsn" {}
variable "varenvpi" {}
variable "varenvni" {}
variable "varenvvm" {}
variable "varenvkv" {}
variable "varenvnsg" {}
variable "varenvnsgni" {}
